# Generated by Django 3.1.5 on 2021-01-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_flow_vcs', '0002_auto_20210117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flowversion_parent', to='ml_flow_vcs.flowversion'),
        ),
    ]
